apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo
  namespace: demo-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/visarnik/DevOpsUpskillDemo.git
    targetRevision: HEAD