apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
      argocd-image-updater.argoproj.io/image-list: demoimage=ncorplab/telerikdemo:latest
      argocd-image-updater.argoproj.io/demoimage.update-strategy: latest
      argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
  source:
    path: kubernetes/devops-demo
    repoURL: https://github.com/visarnik/DevOpsUpskillDemo.git
    targetRevision: HEAD