apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/devops-demo
    repoURL: https://github.com/visarnik/DevOpsUpskillDemo.git
    targetRevision: HEAD