name: Build App

on:
  push:
    branches:
    - main

permissions:
  packages: write

jobs:
  

  build:
    name: 'Build & Push Image'
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9  
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASS}}
      
      - name: Build the Docker image
        env:
          IMAGE_REG: docker.io
          IMAGE_REPO: ncorplab/telerikdemo
          IMAGE_TAG: latest
        run: |
          /usr/bin/docker build . --file ./build/Dockerfile --tag $IMAGE_REG/$IMAGE_REPO:$IMAGE_TAG
      
      
