name: Build App

on:
  push:
    branches:
    - main

permissions:
  packages: write

jobs:
  

  build:
    name: 'Build & Push Image'
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Set current date as env variable
        run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
       
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASS}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
      
      - name: Build the Docker image
        env:
          IMAGE_REG: docker.io
          IMAGE_REPO: ncorplab/telerikdemo
          IMAGE_TAG: ${{ steps.current-time.outputs.time }}
        run: |
          docker build . --file ./build/Dockerfile --tag $IMAGE_REG/$IMAGE_REPO:$IMAGE_TAG
          docker tag $IMAGE_TAG $IMAGE_REG/$IMAGE_REPO:latest
      
      - name: Docker Push
        env:
          IMAGE_REPO: ncorplab/telerikdemo
        run: |
          docker push -a $IMAGE_REPO
      
