name: Build App

on:
  push:
    branches:
    - main

permissions:
  packages: write

jobs:
  

  build:
    name: 'Build & Push Image'
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASS}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
      
      - name: Build the Docker image
        env:
          IMAGE_REG: docker.io
          IMAGE_REPO: ncorplab/telerikdemo
          IMAGE_TAG: latest
        run: |
          docker build . --file ./build/Dockerfile --tag $IMAGE_REG/$IMAGE_REPO:$IMAGE_TAG
      
      - name: Docker Push
        env:
          IMAGE_REPO: ncorplab/telerikdemo
        run: |
          docker push $IMAGE_REPO
      
